#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE gitea WITH LOGIN PASSWORD 'gitea' VALID UNTIL 'infinity';
  CREATE DATABASE gitea WITH ENCODING='UTF8' OWNER=gitea CONNECTION LIMIT=-1; 
EOSQL
